<a href="https://colab.research.google.com/github/ssb-shree/DS-ML/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Arrays
---
**Python List** -> no type safety, slow n less memory efficient

**Numpy array** -> type safe, fast n efficient, easy vector operations

# Creating a Numpy Array


---

In [2]:
import numpy as np

In [8]:
array = np.array([1,2,3,4]) # turns list into array

array([1, 2, 3, 4])

In [9]:
list = [[1,2],[3,4],[5,6]] # does not multi-di array
print(list)
array = np.array(list) # converts list into a multi di array
print(array)

[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]


# Generating an Array


---



In [10]:
np.arange(1, 11, 2) # creates an array from 1 to 11 with step count 2
np.zeros((2,2)) # creates a array of zeros
np.ones((2,2)) # creates a array of ones
np.linspace(0,10,2) # create an evenly spaced array betn 2 numbers

array([1, 3, 5, 7, 9])

# Generating a Random Array


---



In [12]:
np.random.rand(10) # array of elements betn 0 n 1
np.random.randn(10) # array of elements betn -3 n 3
np.random.randint(1, 10, 10) # lowest, highest, no of elements

array([7, 4, 1, 4, 7, 3, 8, 3, 2, 1])

# Numpy Array Attributes


---



In [13]:
arr = np.array([[1,2],[3,4]])
arr.shape # (no of rows, no of cols)
arr.size # no of elements in array
arr.dtype # data type of array elements

4

# Numpy Array Methods


---



In [ ]:
arr.min()
arr.max()

arr.sum() # adds all the element of array

np.sum(arr, axis=0) # for summation of cols axis = 0 for rows exis =1

arr.mean() # mean value of array
arr.std() # standard deviation

arr.argmax() # index of max element
arr.argmin() # index of min element

# Reshaping and Resizing Nump Array


---

**Reshaping** is changing diemensions of an array

**Resizing** is updating the var storing the array with the resized array

In [17]:
arr = np.arange(1,10) # creates an single-di vector
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
 arr = arr.reshape(3,3)
 arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])