<a href="https://colab.research.google.com/github/ssb-shree/DS-ML/blob/main/Numpy/indexingNslicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexing an Silcing an Vector


---



In [1]:
import numpy as np

In [13]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[6]

np.int64(6)

In [10]:
silcedArr = arr[:6]
silcedArr

array([0, 1, 2, 3, 4, 5])

In [17]:
SilcedWithSteps = arr[:7:2]
SilcedWithSteps

array([0, 2, 4, 6])

# Indexing an Silcing Multi-di Array


---



In [20]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr[0] # rows
arr[0,1] # an element of rows

np.int64(2)

In [25]:
silcedArray = arr[1:, 1:]
silcedArray

array([[5, 6],
       [8, 9]])

In [28]:
col = arr[:, 1]
col

array([2, 5, 8])