<a href="https://colab.research.google.com/github/ssb-shree/DS-ML/blob/main/Numpy/operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arithmetic Operations on Numpy Array



---



In [3]:
import numpy as np

In [4]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)

In [5]:
a1+a2
a1-a2
a1/a2
a1//a2 # floor division
a1*a2
a1**a2 # expo

array([      1,     128,    6561,  262144, 9765625])

# Broadcating

In [6]:
arr = np.arange(0,6)
arr + 10

array([10, 11, 12, 13, 14, 15])

# Deep n Shallow Copy


---
**shallow** -> og array wont be updated

**deep** -> og array will be updated



In [7]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# shallow copy
sliced = a[:5]
sliced = sliced * 10
sliced

array([10, 20, 30, 40, 50])

In [9]:
# deep copy
a = np.arange(1,6)
b = a # use a.copy if u dont want deep copy

b[0] =77
a

array([77,  2,  3,  4,  5])

# Matrix Operation

In [10]:
matA = np.arange(1,5).reshape(2,2)
matB = np.arange(5,9).reshape(2,2)

In [11]:
matA @ matB == np.dot(matA, matB) # matrix multiplication

array([[ True,  True],
       [ True,  True]])

In [12]:
matA.T # transpose

array([[1, 3],
       [2, 4]])

# Stacking Arrays


---
we can only stack vectors not arrays


In [13]:
a = np.arange(1,3)
b = np.arange(3,5)

In [16]:
np.vstack((a,b)) # makes matrix of 2 vectors

array([[1, 2],
       [3, 4]])

In [15]:
np.hstack((a,b)) # gives a new vector by joining given vectors

array([1, 2, 3, 4])

In [ ]:
np.column_stack((a,b)) # a gets a col, b gets a col

# Spilting Arrays


---



In [34]:
arr = np.arange(1, 17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
np.hsplit(arr,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [37]:
np.vsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]